FROM kaldiasr/kaldi:latest

WORKDIR /opt/kaldi/src
RUN make ext

ENV SRILM="/opt/kaldi/tools/srilm"
COPY srilm-1.7.3.tar.gz ${SRILM}/srilm-1.7.3.tar.gz
RUN tar -xvf ${SRILM}/srilm-1.7.3.tar.gz --directory ${SRILM}


RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y \
    swig \
    python-pip \
    cmake \
    graphviz \
    ghostscript \
    libasound-dev \
    alsa-utils \
    libasound2 \
    libasound2-plugins \
    pulseaudio \
    pulseaudio-utils \
    vorbis-tools \
    sox \
    && rm -rf /var/lib/apt/lists/* 

RUN pip install numpy 
RUN pip install git+https://github.com/sequitur-g2p/sequitur-g2p@master

WORKDIR ${SRILM}
RUN make
ENV PATH="$PATH:$SRILM/bin/i686-m64/"

WORKDIR /opt/kaldi/tools
RUN ./install_portaudio.sh
WORKDIR /opt/kaldi/tools/portaudio
RUN ./configure && make

WORKDIR /opt/kaldi